### ISSUE TITLE
Google Calendar API: Invalid Time format in POST request

### ISSUE THREAD

**Issue by dkomarov** [567WebSystems/project2alpha#11]
When I tried to making a Post request to http://localhost:3000/. This is what the console shows:

<img width="1256" alt="Screen Shot 2020-02-26 at 5 44 16 PM" src="https://user-images.githubusercontent.com/21226482/75398602-c24c4e80-58bf-11ea-942f-a1ae31860c6c.png">

There seems to be an issue with the time-stamp, yet again (as in when we first tried to code adding an event).

Any ideas on how to resolve?

**Comment by dkomarov** [comment]
After modifying the contents of the Post request, I was able to successfully create an event outside of the website, using Postman instead:

<img width="1039" alt="Screen Shot 2020-02-27 at 12 44 33 AM" src="https://user-images.githubusercontent.com/21226482/75419097-b0d46800-58fa-11ea-8b12-c08cb230ef23.png">

When the data is sent in the proper format, the error does not appear. If anyone has any issues regarding this, feel free to post below!

**Comment by dhirajj14** [comment]
The format accepted by the google calendar is ISO 8601. So we need to covert over date and time from the html form into the ISO 8601.
https://en.wikipedia.org/wiki/ISO_8601

**Comment by dkomarov** [comment]
Thanks for providing the link! Should add more to this review later on.

**Comment by dkomarov** [comment]
We will reference:
https://www.w3schools.com/jsref/jsref_toisostring.asp

**Comment by dkomarov** [comment]
This was fixed with: https://github.com/567WebSystems/project2alpha/commit/95ae50e5e24658133108c27fd3ecd3aecfea381d
