### ISSUE TITLE
Dates are concatenating & GAPI not accepting them

### ISSUE THREAD

**Issue by dkomarov** [567WebSystems/project2alpha#18]
<img width="704" alt="concatDates" src="https://user-images.githubusercontent.com/21226482/76058724-c8d36980-5f42-11ea-9117-3a6c13fa8392.png">

2 of 3 team members ran into this issue. Please post any solutions or ideas you have down below in the comments. Thank you.

**Comment by dhirajj14** [comment]
This was fixed with: 99d7bf617e57f80ea4ad6384f87f425572e736c3
